services:
  - type: web
    name: musica-backend
    env: node
    buildCommand: npm install && npm --prefix shared run build && npm --prefix server run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        value: https://musica-apvs.vercel.app
      - key: DATA_DIR
        value: /var/data/musica
    disk:
      name: musica-data
      mountPath: /var/data/musica
      sizeGB: 1
